### ISSUE TITLE
Category selector should use category selector module

### ISSUE THREAD

**Issue by julianlam** [NodeBB/nodebb-plugin-feed#9]
:eyes: 

![image](https://github.com/user-attachments/assets/65928ab5-ee82-498e-aa72-d2518554a9de)

**Comment by barisusakli** [comment]
Where is this category selector?

**Comment by julianlam** [comment]
The core module for selecting a category in composer, for example .

**Comment by julianlam** [comment]
Oh sorry, wrong repo. This should go in rss

**Comment by julianlam** [comment]
https://github.com/barisusakli/nodebb-plugin-rss/issues/67
